version: 2
references:

  cache_key: &cache_key
    key: cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  workspace: &workspace
               ~/workspace
  attach_release_workspace: &attach_release_workspace
    attach_workspace:
      at: *workspace
  persist_release_workspace: &persist_release_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - .

  decrypt: &decrypt
    run:
      name: Decrypting secret keys
      command: |
        sh secrets/decrypt-keys.sh $SECRET_ANDROID
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - *decrypt
      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Gradle build (release)
          command: ./gradlew bundleRelease
      - *persist_release_workspace
      - store_artifacts:
          path: app/build/outputs/bundle/
          destination: /bundle/
      - store_artifacts:
          path: app/build/outputs/mapping/
          destination: /mapping/

  deploy_staging:
    <<: *android_config
    steps:
      - *attach_release_workspace
      - *restore_cache
      - run:
          name: Deploy to App Distribution
          command: ./gradlew assembleRelease appDistributionUploadRelease

  deploy:
    <<: *android_config
    steps:
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Execute fastlane
          command: bundle exec fastlane playstore

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*/
      - deploy_staging:
          filters:
            tags:
              only: /^v\d+[.]\d+[.]\d+(-staging){0,1}$/
          requires:
            - build
      - deploy:
          filters:
            tags:
              only: /^v\d+[.]\d+[.]\d+$/
            branches:
              ignore: /^.*/
          requires:
            - build